name: AUTOPKG

on:
  workflow_dispatch:
jobs:
  install_autopkg:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Autopkg
      run: |
        curl -LJO https://github.com/autopkg/autopkg/releases/download/v2.7.2/autopkg-2.7.2.pkg

    - name: Install Autopkg
      run: |
        sudo installer -pkg autopkg-2.7.2.pkg -target /
        
    - name: Add Repo For JamfUploader Processor
      run: |
        autopkg repo-add grahampugh-recipes
        
    - name: Add Repo For Testing Purpose
      run: |
        autopkg repo-add killahquam-recipes
        
    - name: Configure Autopkg
      run: |
        defaults write ~/Library/Preferences/com.github.autopkg.plist JSS_URL "${{ secrets.JSS_URL }}"
        defaults write ~/Library/Preferences/com.github.autopkg.plist API_USERNAME ${{ secrets.API_USERNAME }}
        defaults write ~/Library/Preferences/com.github.autopkg.plist API_PASSWORD ${{ secrets.API_PASSWORD }}
    
    - name: Do a testrun
      run: |
        autopkg run -v VisualStudioCode.jamf
