name: AUTOPKG

on:
  workflow_dispatch:
jobs:
  install_autopkg:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Autopkg
      run: |
        curl -LJO https://github.com/autopkg/autopkg/releases/download/v2.7.2/autopkg-2.7.2.pkg

    - name: Install Autopkg
      run: |
        sudo installer -pkg autopkg-2.7.2.pkg -target /
